### ISSUE TITLE
1.7.10 compatibility

### ISSUE THREAD

**Issue by SrYthan** [NextPlugins/NextCash#8]
Would it be possible to make this plugin compatible with version 1.7.10?

Teria possibilidade de fazer com que este plugin seja compatível com a versão 1.7.10 ?

### [03:02:24 INFO]: [NextCash] Enabling NextCash v1.2.7
[03:02:24 INFO]: [NextCash] Iniciando carregamento do plugin.
[03:02:24 ERROR]: Error occurred while enabling NextCash v1.2.7 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.base.Stopwatch.createStarted()Lguava10/com/google/common/base/Stopwatch;
        at com.nextplugins.cash.NextCash.onEnable(NextCash.java:81) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-master-ever-2-552106c]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:362) [JavaPluginLoader.class:1.7.10-master-ever-2-552106c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:409) [SimplePluginManager.class:1.7.10-master-ever-2-552106c]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:402) [CraftServer.class:1.7.10-master-ever-2-552106c]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:336) [CraftServer.class:1.7.10-master-ever-2-552106c]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:513) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:487) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:447) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by eikefab** [comment]
Infelizmente, a 1.7.10 é MUITO defasada (poxa, versão de 2013 em 2022?) e pouquíssima gente usa. Sem contar que algumas funcionalidades (como a do erro que você apresentou) não estão presentes no Spigot da 1.7.10; então teríamos de alterar muita coisa pra algo que, como eu disse antes, pouquíssima gente usa. Os dados do [bstats](https://bstats.org/global/bukkit) mostram que apenas 0.7% dos servidores de Minecraft usam essa versão. 

Sentimos muito.

**Comment by SrYthan** [comment]
entendo o trabalho queriam, mas a 1.7.10 tem um público bastante grande para mods, que é o meu caso.
cerca de 50 players diariamente com 140 mods, por isso o interesse neste plugin, eu utilizo ele na 1.12.2 e é ótimo e gostaria de utilizar também na 1.7.10 e se possível também na 1.5.2, ambos com mods.
